### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by shibamon48** [shibamon48/Exploration_record#30]

**Comment by shibamon48** [comment]
■Webアプリの概要
今まで通ったことのある道を可視化して図鑑のように楽しんだり、散歩に取り入れたい事のメモを付けられる、探索のサポートをテーマとしたサービスです。

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

■MVPリリースまで
- [ ] 環境構築
- [ ] CSS関連の導入
- [ ] デプロイ
- [ ] トップページの作成
- [ ] ユーザー登録
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] マップ画面の作成
- [ ] マップ画面の表示（機能の実装）
- [ ] Roads APIの検証
- [ ] ルートの作成（地点の手入力）
- [ ] ルートの編集
- [ ] ピンの設置
- [ ] スポットの編集

■MVP後
- [ ] マイページ画面
- [ ] パスワードリセット（Sorcery）
- [ ] 旅先リストCRUD機能
- [ ] GoogleMap
- [ ] Xでのシェア機能
- [ ] マップの拡大縮小に伴う表示の変更
- [ ] 現在地取得
- [ ] Googleログイン調査
- [ ] Googleログイン実装

■MVPレビュー依頼予定日
予定日：2024年 9月 25日

**Comment by shibamon48** [comment]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。

■ProjectsのURL
https://github.com/users/shibamon48/projects/1/views/1?sumFields=%5B127263863%5D&hideItemsCount=false&pane=issue&itemId=76271681

■MVPリリースまで
- [ ] rails new
- [ ] Herokuにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] xxx投稿機能
- [ ] AIによるコメント機能

■MVP後
- [ ] GoogleMap
- [ ] オートコンプリート検索昨日
- [ ] SNSログイン（Googleログイン）
- [ ] LINE通知
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] CI（GitHubActions）
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] OGP（静的）
- [ ] ...

■MVPレビュー依頼予定日
予定日：20xx年 ◯月 X日

**Comment by TakenakaEri** [comment]
提出ありがとうございます！

ストーリーポイントが5の部分がもう少し細分化できそうな気がするので、調査と実装を分けて記載してください。
また、issueは上から順番に着手するように並べ替えて提出をお願いします。（今のところ、大丈夫そうな気がしておりますが、念の為）

**Comment by shibamon48** [comment]
確認ありがとうございます！
現在地取得に関して、調査と実装に分けて記載いたしました。
ご確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- マイページ
- Xシェア
- マップの拡大縮小
- パスワードリセット
- Googleログイン
